### ISSUE TITLE
Washer Dryer control

### ISSUE THREAD

**Issue by markymark125** [nVuln/homebridge-lg-thinq#121]
<!--
First, You need enable Homebridge debug mode, check debug logging and you can see something like this:
```
[LGThinQ] Found device: 	
LG V11 FWV1128WTSA EZDispense

if device currently not supported, maybe
```
[LGThinQ] Device not supported:  xxx-xxx-xxx-xxx-xxx: Dryer (DRYER xxxxxxxx)
[LGThinQ] device data: *********************
```
-->

	
I would like full control of the washer dryer - LG V11 FWV1128WTSA EZDispense.

Please let me know if you would like to test the plug-in 

<!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->


<!-- A clear and concise description of what you want to happen. Ex. I want to control the washer dryer... -->

**Device Data:**
<!-- Put a device data in debug log here. -->


<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by MarkMorrow** [comment]
Mine are LG Washer Model# WM4000HWA, Dryer Model # DLGX4001W.  Currently they show a on/off toggle which does not work (as expected).  If control can be added I too can help test.  If it can't perhaps the toggle can be removed so reduce confusion and an appliance icon displayed instead of a water tap.  This is what is currently what is seen from Homekit:
![Homekit](https://user-images.githubusercontent.com/6678604/153007904-a0ff5856-0a50-4038-9ec2-37a58afe228e.jpeg)
![Device](https://user-images.githubusercontent.com/6678604/153007920-48fdcbae-fd22-4a9f-8d2d-19ff8d07c288.jpeg)

**Comment by markymark125** [comment]
Same as I have.  Not able to control the appliance yet just monitor it,

Hopefully there will be more added to this plugin

**Comment by nVuln** [comment]
I know, but problem is washer need turn on remote control feature, and this feature always turned off when washer is off, we need enable it by manual 🥲
I mean we can't enable remote control permanently (or maybe this problem only in my washer 😢, just try it on native lg app)

**Comment by markymark125** [comment]
Hi @nVuln 

Correct,remote start needs to be manually activated on the machine each time thus allowing the LG app to control start/stop

However the plugin still doesn't control the washer dryer when remote start is turned on,

Any ideas? 

Again happy to share logs etc
