### ISSUE TITLE
Washer/Dryer - Switch instead of vave

### ISSUE THREAD

**Issue by ghost** [nVuln/homebridge-lg-thinq#229]
For a washer/dryer, it would be amazing if these were displayed as switches, not valves.

At least with my homekti implementation, I can not start automation based on a valve.   I would like to be able to turn on/off or control a device when the load/cycle starts and/or stops.

**Comment by nVuln** [comment]
1. washer/dryer on thinq 2 cannot turn on/off remotely
2. if we change to Switch instead of Valve, remaining time will not show up, a lot of ppl want to know this
3. we have program finished event as occupancy sensor, you can setup automation on it

Sorry, we cannot serve your request
tell me if you have anymore question

**Comment by schlundg** [comment]
I think my request was mis-stated.    I want to control other devices based on the running/stopped (closed/open) state.    

I do not wish to control the dryer, I wish to control a device based on the dryer's status....

**Comment by nVuln** [comment]
@schlundg if your washer/dryer running on thinq 2, you can turn on door lock feature and create automation based on that, when load/cycle started, door will be locked
