### ISSUE TITLE
What is an LG device ID, and how to find it?

### ISSUE THREAD

**Issue by aditya298** [nVuln/homebridge-lg-thinq#42]
I want to add just the fridge, but not the washer/dryer set that I own, but I have no idea what a "device id" is. It doesn't say in the README

**Comment by nVuln** [comment]
did you used `homebridge-config-ui-x` ? I already implement config GUI for this, in Setting page it's will load all device, just remove which device you want
otherwise, turn on homebridge debug mode, you can see all device data (id included) in debug logging
<img width="453" alt="Screen Shot 2021-08-07 at 1 32 05 PM" src="https://user-images.githubusercontent.com/54855446/128644984-afdfe3aa-8d59-4216-be6f-f1343aabb4e2.png">
